### ISSUE TITLE
#define 은 함수를 선언하는 방식이 아니라 매크로 방식임

### ISSUE THREAD

**Issue by limdongjin** [pixar0407/data_structure_on_c#1]
https://github.com/pixar0407/data_structure_on_c/blob/f47e736fd7e406a0dea557947de0a3501dcddae7/README.md#L43-L51

단순히 SWAP(x,y,t)형태의 코드를 컴파일 이전 전처리(preprocess)하는 과정에서 ((t)=(x),(x)=(y),(y)=(t))로 코드자체를 바꿔치기 해줌. 
그래서 SWAP(list[i], list[j], temp); 는 컴파일 이전 전처리하는 과정에서 tmp=list[i], list[i]=list[j], list[j]=tmp; 라는 코드로 바뀌게됨. 그래서 사실상 함수를 호출하는 형태가 아닌, 단순히 코드를 바꿔치기하는 매크로임.

```c
#include <stdio.h>
 #define printf scanf
 int main(){
     int a = 1;
     printf("%d", a);
 }
```
그래서 위와 같은 코드는 컴파일 타임 에러가 발생하지않고, 
프로그램을 실행하면 printf대신 scanf가 실행됨. 전처리 타임에서 printf는 scanf로 바꿔치기 됬으므로... 
컴파일타임시점에서는 컴파일러는 저 코드를 받게되면 printf가 아니라 scanf라고 작성된 코드를 받게됨.

결국 저 swap코드는 parameter passing자체가 아님. 그냥 저 define에 있는 코드 복붙되는 개념

## Reference

[cppreference >>> macro ](https://en.cppreference.com/w/cpp/preprocessor/replace)

**Comment by pixar0407** [comment]
감사합니다. reference로 잘 공부해 보겠습니다.
